# Generated by Django 4.2 on 2023-07-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeninja", "0004_alter_recipe_image_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuisine",
            name="cover",
            field=models.ImageField(
                default=None, upload_to="recipeninja/images/cuisine_covers"
            ),
            preserve_default=False,
        ),
    ]
