# Generated by Django 4.2 on 2023-07-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeninja", "0005_cuisine_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
