# Generated by Django 4.2 on 2023-07-19 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipeninja", "0007_difficulty_recipe_est_calories_recipe_est_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="difficulty",
            options={
                "verbose_name": "Difficulty",
                "verbose_name_plural": "Difficulties",
            },
        ),
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipes",
                to="recipeninja.difficulty",
            ),
            preserve_default=False,
        ),
    ]
