# Generated by Django 4.2 on 2023-07-19 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeninja", "0008_alter_difficulty_options_alter_recipe_difficulty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="est_time",
            new_name="est_duration",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="est_calories",
        ),
        migrations.AddField(
            model_name="recipe",
            name="est_carbs",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="est_fat",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="est_protein",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
