# Generated by Django 4.2 on 2023-07-24 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeninja", "0010_recipe_servings"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="likers",
            field=models.ManyToManyField(
                blank=True, related_name="liked_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
