# Generated by Django 4.2 on 2023-07-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeninja", "0011_comment_likers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="banner",
            field=models.ImageField(
                blank=True, null=True, upload_to="recipeninja/images/banner"
            ),
        ),
    ]
